services:
  db:
    image: mysql:8.0
    container_name: prueba_tecnica_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: prueba_tecnica_backend
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass_123
      MYSQL_ROOT_PASSWORD: root_pass_123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot_pass_123"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data: